version: '3.7'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=EnsaB
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: EnsaB
    networks:
      - my_network
    depends_on:
      - mongodb

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:
